"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { menuItems } from "@/constants/menuItems";
import { usePathname } from "next/navigation";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrapper for the entire page */}
        <div className="min-h-screen flex flex-col">
          {/* Header stays fixed at the top */}
          <Header
            title={
              pathname === "/"
                ? "Home"
                : menuItems.find((item) => item.href === pathname)?.label ||
                  "Page"
            }
          />

          {/* This ensures the header doesn't overlap the content */}
          <main className="flex-1 p-4 pt-20">{children}</main>
        </div>
      </body>
    </html>
  );
}
